name: 'Wait'
description: 'Wait a designated number of milliseconds'
inputs:
  github-token:
    description: 'GitHub token for OctoKit client'
  name:
    description: 'Name of the project'
  description:
    description: 'Project description'
  private:
    description: 'Sets project visibility to public or private'
    required: true
    default: false
  columns:  # project board column names
    description: 'Define the columns for your board'
    required: true
    default: |
      Backlog
      In progress
      Done
outputs:
  project-id:
    description: 'ID of the board you created'
runs:
  using: 'node12'
  main: 'dist/index.js'
