name: 'Wait'
description: 'Wait a designated number of milliseconds'
inputs:
  name:
    description: 'Name of the project'
  columns:  # project board column names
    description: 'Define the columns for your board'
    required: true
    default: |
      Backlog
      In progress
      Done
outputs:
  project_id:
    description: 'ID of the board you created'
runs:
  using: 'node12'
  main: 'dist/index.js'
